    <!-- Jquery JS-->
    <script src="<?= _assets ?>/CoolAdmin/vendor/jquery-3.2.1.min.js"></script>
    <!-- Bootstrap JS-->
    <script src="<?= _assets ?>/CoolAdmin/vendor/bootstrap-4.1/popper.min.js"></script>
    <script src="<?= _assets ?>/CoolAdmin/vendor/bootstrap-4.1/bootstrap.min.js"></script>
    <!-- Vendor JS       -->
    <script src="<?= _assets ?>/CoolAdmin/vendor/slick/slick.min.js">
    </script>
    <script src="<?= _assets ?>/CoolAdmin/vendor/wow/wow.min.js"></script>
    <script src="<?= _assets ?>/CoolAdmin/vendor/animsition/animsition.min.js"></script>
    <script src="<?= _assets ?>/CoolAdmin/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
    </script>
    <script src="<?= _assets ?>/CoolAdmin/vendor/counter-up/jquery.waypoints.min.js"></script>
    <script src="<?= _assets ?>/CoolAdmin/vendor/counter-up/jquery.counterup.min.js">
    </script>
    <script src="<?= _assets ?>/CoolAdmin/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="<?= _assets ?>/CoolAdmin/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="<?= _assets ?>/CoolAdmin/vendor/chartjs/Chart.bundle.min.js"></script>
    <script src="<?= _assets ?>/CoolAdmin/vendor/select2/select2.min.js">
    </script>

    <!-- Mask -->
    <script src="<?= _assets ?>/CoolAdmin/js/jQuery-Mask-Plugin-master/dist/jquery.mask.min.js"></script>

    <!-- Main JS-->
    <script src="<?= _assets ?>/CoolAdmin/js/main.js"></script>