        <!-- HEADER MOBILE-->
        <header class="header-mobile d-block d-lg-none">
            <div class="header-mobile__bar">
                <div class="container-fluid">
                    <div class="header-mobile-inner">
                        <a class="logo" href="index.html">
                            <img src="<?= _assets ?>/CoolAdmin/images/icon/logomarca_C_douggs.png" alt="CoolAdmin" />
                        </a>
                        <button class="hamburger hamburger--slider" type="button">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>

        <!-- MENU MOBILE SIDEBAR-->   

        <?php $this->partial("permission\\admin\\controllers\\menuMobileSidebar"); ?>

        <!-- MENU mOBILE SIDEBAR-->
        </header>
        <!-- END HEADER MOBILE-->

        <!-- MENU SIDEBAR-->

        <?php $this->partial("permission\\admin\\controllers\\menuSidebar"); ?>

        <!-- MENU SIDEBAR-->