<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>DOUGGS</title>

    <!-- STYLES START -->

    <?php $this->partial("heartwood\\common\\layouts\\controllers\\styles"); ?>

    <!-- STYLES END -->

</head>

<body class="animsition">
    <div class="page-wrapper">

        <!-- ALERTS START -->

            <?php $this->partial("heartwood\\common\\layouts\\controllers\\messages"); ?>

        <!-- ALERTS END -->
        
        <div class="page-content--bge5">
            <div class="container">
                <div class="login-wrap">
                    <div class="login-content">
                        <div class="login-logo">
                            <a href="#">
                                <img src="<?= _assets ?>/CoolAdmin/images/icon/logomarca_douggs.png" alt="DOUGGS">
                            </a>
                        </div>

                        <!-- Start Status area -->
        
                        <?php $this->content(); ?>
                        
                        <!-- End Status area-->
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- SCRIPTS START -->

    <?php $this->partial("heartwood\\common\\layouts\\controllers\\scripts"); ?>

    <!-- SCRIPTS END -->

</body>

</html>
<!-- end document-->